# Generated by Django 2.0.13 on 2019-07-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='pen_name',
            field=models.CharField(default='input', max_length=200),
            preserve_default=False,
        ),
    ]
