# Generated by Django 2.0.13 on 2019-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190713_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
